#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "Mason Rhodes"
email = "user@example.com"

[ui]
editor = "zed --wait"
diff-editor = "nvim -d"
merge-editor = "nvim -d"
pager = "less -FRX"
