[terminal]
# The VT to run the greeter on. Can be "next", "current" or a number
vt = 1

[default_session]
# gtkgreet with GTK4 and custom CSS
command = "gtkgreet -l -s /etc/greetd/gtkgreet.css"

# The user to run the greeter as
user = "greeter"

[initial_session]
# Uncomment to auto-login on first boot
# command = "Hyprland"
# user = "mason"
