[terminal]
# The VT to run the greeter on. Can be "next", "current" or a number
vt = 1

[default_session]
# regreet - GTK4 greeter running under Hyprland compositor
# Hyprland config: /etc/greetd/hypr.conf
# regreet config: /etc/greetd/regreet.toml
command = "env LIBSEAT_BACKEND=seatd Hyprland --config /etc/greetd/hypr.conf"

# The user to run the greeter as
user = "greeter"
